// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    XAntButton: typeof import('./src/components/antd/xAntButton.vue')['default']
    XApplicationItem: typeof import('./src/components/vant/xApplicationItem.vue')['default']
    XButton: typeof import('./src/components/vant/xButton.vue')['default']
    XCascader: typeof import('./src/components/antd/xCascader.vue')['default']
    XCheckbox: typeof import('./src/components/vant/xCheckbox.vue')['default']
    XCheckBox: typeof import('./src/components/antd/xCheckBox.vue')['default']
    XDatePicker: typeof import('./src/components/antd/xDatePicker.vue')['default']
    XDateTimePicker: typeof import('./src/components/vant/xDateTimePicker.vue')['default']
    XImage: typeof import('./src/components/xImage.vue')['default']
    XInput: typeof import('./src/components/antd/xInput.vue')['default']
    XInputNumber: typeof import('./src/components/antd/xInputNumber.vue')['default']
    XNormalInput: typeof import('./src/components/xNormalInput.vue')['default']
    XPicker: typeof import('./src/components/vant/xPicker.vue')['default']
    XRadio: typeof import('./src/components/antd/xRadio.vue')['default']
    XSearch: typeof import('./src/components/vant/xSearch.vue')['default']
    XSelect: typeof import('./src/components/antd/xSelect.vue')['default']
    XStepper: typeof import('./src/components/vant/xStepper.vue')['default']
    XSvg: typeof import('./src/components/xSvg.vue')['default']
    XView: typeof import('./src/components/xView.vue')['default']
  }
}
